name: Go

on:
  push:
    branches:
      - master
    tags:
      - v1.1

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Test
      run: make test

    - name: Build
      run: make build

    - name: GH Release
      uses: softprops/action-gh-release@v0.1.5
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          darwin-amd64-yamllint.zip
          linux-amd64-yamllint.zip
          windows-amd64-yamllint.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
